
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python configuration
python:
  version: "3.11"  # Latest version at time of deployment
  install:
    - method: setuptools  # Default install method
